version: '3.8'

services:
  # 1. The Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: maintainx_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: maintainx
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. The Message Broker (Mosquitto MQTT)
  mqtt:
    image: eclipse-mosquitto:2
    container_name: maintainx_mqtt
    ports:
      - "1883:1883"  # MQTT Port
      - "9001:9001"  # WebSockets Port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

volumes:
  postgres_data: